/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kuis2PBO;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.text.*;
import java.util.*;

/**
 *
 * @author Rahmad Dwi Ferdyan
 */
public class Kuis2 extends javax.swing.JFrame {

    private JLabel errorLabel;

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
        addListeners();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nikText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lakiRadio = new javax.swing.JRadioButton();
        perempuanRadio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        notelpText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ttlText = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        ipkField = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        namaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextActionPerformed(evt);
            }
        });

        alamatText.setColumns(20);
        alamatText.setRows(5);
        jScrollPane1.setViewportView(alamatText);

        jLabel4.setText("Jenis Kelamin");

        buttonGroup1.add(lakiRadio);
        lakiRadio.setText("Laki-laki");
        lakiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioActionPerformed(evt);
            }
        });
        lakiRadio.setActionCommand("Laki-laki");

        buttonGroup1.add(perempuanRadio);
        perempuanRadio.setText("Perempuan");
        perempuanRadio.setActionCommand("Laki-laki");

        jLabel5.setText("Hobi");

        jCheckBox1.setText("Membaca");

        jCheckBox2.setText("Olahraga");

        jCheckBox3.setText("Kesenian");

        jLabel6.setText("No. Telp");

        notelpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notelpTextActionPerformed(evt);
            }
        });
        notelpText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                notelpTextKeyReleased(evt);
            }
        });
        notelpText.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();

                if (!Character.isDigit(c)) {
                    e.consume();
                }
            }
        });

        jLabel7.setText("Tanggal Lahir");

        ttlText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttlTextActionPerformed(evt);
            }
        });

        jLabel8.setText("Pendidikan Terakhir");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4/ S1", "S2", "S3" }));
        jComboBox1.setSelectedIndex(-1);

        jLabel9.setText("IPK");

        ipkField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipkFieldActionPerformed(evt);
            }
        });
        ipkField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ipkFieldKeyReleased(evt);
            }
        });

        jButton1.setText("Daftar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 161, Short.MAX_VALUE)
                            .addComponent(ipkField)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(notelpText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ttlText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lakiRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(perempuanRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lakiRadio)
                        .addComponent(perempuanRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox2)
                        .addComponent(jCheckBox3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(notelpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ttlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ipkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addListeners() {
        nikText.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent e) {
                validateNik();
            }
        });

        ttlText.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent e) {
                validateAge();
            }
        });

        ipkField.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent e) {
                validateIPK();
            }
        });

        jComboBox1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                validatePendidikan();
            }
        });

        notelpText.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent e) {
                validatePhone();
            }
        });
    }

    // Method validasi NIK
    private void validateNik() {
        if (nikText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIK tidak boleh kosong");
        }
    }

    // Method validasi Usia
    private void validateAge() {
        if (!checkAge()) {
            JOptionPane.showMessageDialog(this, "Anda belum cukup umur untuk melamar pekerjaan ini");
        }
    }

    // Method validasi IPK
    private void validateIPK() {
        if (!checkIPK()) {
            JOptionPane.showMessageDialog(this, "IPK tidak valid");
        }
    }

    // Method validasi Pendidikan
    private void validatePendidikan() {
        String pendidikan = jComboBox1.getSelectedItem().toString();
        if (pendidikan.equals("D1") && Float.parseFloat(ipkField.getText()) < 3.01) {
            JOptionPane.showMessageDialog(this, "Pendidikan minimal D1 dengan IPK minimal 3,01");
        }
    }

    // Method validasi No Telepon
    private void validatePhone() {
        try {
            Long.parseLong(notelpText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nomor telepon hanya boleh angka");
        }
    }

    // Method untuk cek usia
    private boolean checkAge() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date birthDate = sdf.parse(ttlText.getText());
            Calendar cal = Calendar.getInstance();
            cal.setTime(birthDate);
            int birthYear = cal.get(Calendar.YEAR);
            int age = Calendar.getInstance().get(Calendar.YEAR) - birthYear;
            return age >= 18;
        } catch (ParseException ex) {
            return false;
        }
    }

    // Method untuk cek IPK
    private boolean checkIPK() {
        try {
            float ipk = Float.parseFloat(ipkField.getText());
            return ipk >= 0.0 && ipk <= 4.0;
        } catch (NumberFormatException e) {
            return false;
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(checkIPK()){
          nikText.setText("");
        namaText.setText("");
        alamatText.setText("");
        notelpText.setText("");
        ttlText.setText("");
        ipkField.setText("");
        jComboBox1.setSelectedIndex(-1);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        lakiRadio.setSelected(false);
        perempuanRadio.setSelected(false);  
         JOptionPane.showMessageDialog(null, "Anda berhasil Mendaftar");
        } else {
            ipkField.setText("");
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lakiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioActionPerformed

    private void namaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextActionPerformed

    private void notelpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notelpTextActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_notelpTextActionPerformed

    private void notelpTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notelpTextKeyReleased
        String input = notelpText.getText();

        // Hanya menyisakan angka di dalam JTextField
        input = input.replaceAll("[^\\d]", ""); // Menghapus semua karakter selain angka
        notelpText.setText(input);        // TODO add your handling code here:
    }//GEN-LAST:event_notelpTextKeyReleased

    private void ttlTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttlTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttlTextActionPerformed

    private void ipkFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipkFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipkFieldActionPerformed

    private void ipkFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipkFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ipkFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Kuis2().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField ipkField;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lakiRadio;
    private javax.swing.JTextField namaText;
    private javax.swing.JTextField nikText;
    private javax.swing.JTextField notelpText;
    private javax.swing.JRadioButton perempuanRadio;
    private javax.swing.JFormattedTextField ttlText;
    // End of variables declaration//GEN-END:variables
}
